# Generated by Django 3.1.1 on 2020-10-20 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='User X', max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=200)),
                ('major', models.CharField(max_length=200)),
                ('age', models.IntegerField(default=0)),
                ('description', models.CharField(default='', max_length=200)),
                ('picture', models.ImageField(upload_to='uploads/')),
            ],
        ),
    ]
