# Generated by Django 3.1.1 on 2020-10-19 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=200)),
                ('major', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('description', models.CharField(max_length=200)),
            ],
        ),
    ]
