# Generated by Django 3.1.1 on 2020-10-19 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtualstuddybuddy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='age',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='description',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='major',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(default='User X', max_length=20),
        ),
    ]
