# Generated by Django 3.1.1 on 2020-10-21 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtualstuddybuddy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.CharField(default='Description X', max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(default='Gender X', max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='major',
            field=models.CharField(default='Major X', max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(default='Name X', max_length=50),
        ),
    ]
