# Generated by Django 3.1.1 on 2020-10-20 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtualstuddybuddy', '0002_auto_20201019_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='description',
            field=models.CharField(default='Description X', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(default='Gender X', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='major',
            field=models.CharField(default='Major X', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='Name X', max_length=50),
        ),
    ]
