# Generated by Django 3.1.1 on 2020-11-18 23:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('virtualstuddybuddy', '0005_auto_20201115_1504'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupInbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='virtualstuddybuddy.studygroup')),
            ],
        ),
        migrations.CreateModel(
            name='GroupMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_username', models.CharField(default='', max_length=20, validators=[django.core.validators.MinLengthValidator(3)])),
                ('recipient_group', models.CharField(default='', max_length=20, validators=[django.core.validators.MinLengthValidator(3)])),
                ('message', models.CharField(default='', max_length=1000)),
                ('groupinbox', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='virtualstuddybuddy.groupinbox')),
            ],
        ),
    ]
