# Generated by Django 3.1.1 on 2020-11-19 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('virtualstuddybuddy', '0005_auto_20201115_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermessage',
            name='useroutbox',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='virtualstuddybuddy.profile'),
        ),
    ]
