# Generated by Django 3.1.1 on 2020-11-19 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('virtualstuddybuddy', '0006_groupinbox_groupmessage'),
        ('virtualstuddybuddy', '0006_usermessage_useroutbox'),
    ]

    operations = [
    ]
